/**
 * The deployed Worker: SvelteKit's build output for requests, plus a cron
 * handler that publishes scheduled posts. Bundled by wrangler after
 * `vite build`, so it imports the server modules by relative path.
 */
// @ts-ignore Generated by `vite build`.
import sveltekit from '../.svelte-kit/cloudflare/_worker.js';
import type { Env } from '../src/lib/server/env.ts';
import { cleanUp, publishDue } from '../src/lib/server/scheduler.ts';

export default {
  fetch: sveltekit.fetch,

  async scheduled(_controller: unknown, env: Env, ctx: { waitUntil(p: Promise<unknown>): void }) {
    await publishDue(env);
    // Housekeeping once an hour is plenty.
    if (new Date().getUTCMinutes() === 0) ctx.waitUntil(cleanUp(env));
  },
};
